on:
  push:
    branches: ["develop"]

  workflow_dispatch:

env:
  VERSION: ${{github.sha}}
  ECR_URI: 381491925979.dkr.ecr.ap-northeast-2.amazonaws.com/jabiseo-be # docker ecr 주소
  NAME: jabiseo-was # docker service name

jobs:
  build-push:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "oracle"

      - name: save into application.properties
        env:
          DEV_VARIABLES: ${{ toJson(secrets) }}
        run : |
          echo "$DEV_VARIABLES" | jq -r 'to_entries | 
          map(select(.key | startswith("DEV_")))[] | "\(.key | sub("^DEV_"; ""))=\(.value)"' > ./jabiseo-api/src/main/resources/application.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: gradle build
        run: |
          echo "GRADLE BUILD START==============" \
          ./gradlew jabiseo-api:clean \
          ./gradlew jabiseo-api:build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ECR_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ECR_SECRET_KEY }}
          aws-region: ap-northeast-2


      - name: setup dockerImage name
        run: |
          GIT_TAG=${GITHUB_REF#refs/tags/} 
          DATE=$(date +'%Y%m%d') 
          COMMIT_SHA=$(git rev-parse --short HEAD) 
          dockerImage="${{env.ECR_URI}}:${GIT_TAG}-${DATE}-${COMMIT_SHA}"
          echo "${GITHUB_REF}"
          echo "${GITHUB_REF#refs/}"
          echo "git_tag=${GIT_TAG}"
          echo "sha = ${COMMIT_SHA}"
          echo "dockerImage=${dockerImage}" 
          echo "dockerImage=${dockerImage}" >> $GITHUB_ENV

      - name: Set Up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Cache Docker Layer
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache # cache의 대상을 정한다.
          key: "${{runner.os}}-buildx-${{env.version}}"
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: build and push
        uses: docker/build-push-action@v4
        with:
          context: ./jabiseo-api/
          builder: ${{steps.buildx.outputs.name}}
          push: true
          tags: ${{env.dockerImage}}
